#!/bin/bash
# Single source of truth for release metadata. Sourced by build/install/release.
# Bump VERSION here; release.sh refuses to publish a tag that already exists.

APP_NAME="Touchdown"
BUNDLE_ID="com.bencolson.touchdown"
VERSION="1.5.0"

REPO="bencolson/Touchdown"

# The appcast Sparkle polls. Served from the repo so there is no Pages setup;
# raw.githubusercontent caches for ~5 minutes, which is fine for a daily check.
FEED_URL="https://raw.githubusercontent.com/$REPO/main/appcast.xml"

# EdDSA public key. Its private half lives in the login Keychain as
# "Private key for signing Sparkle updates" -- generated by
# vendor/sparkle/bin/generate_keys and never committed.
PUBLIC_ED_KEY="dKdY7grjiZOlO2HNAen7eo11h77rHSnpT1Z1EhEjbrM="
